### ISSUE TITLE
使用ML.Net 做一个人脸检测

### ISSUE THREAD

**Issue by 292390450** [InCerryGit/.NET-Weekly#1]
- 使用ML.Net 做一个人脸检测
- 文章地址： https://mp.weixin.qq.com/s?__biz=MzU1MDI5MDIzMw==&mid=2247483667&idx=1&sn=c925a979a860f7851d4376c45364a8de&chksm=fba39745ccd41e53515f71a3461fcebe34d25cd159a5322369bcc2f47d33f0d6ad2379e59a50#rd
- ML.Net使用现成的模型对图像进行人脸检测，并标记。

- [x] 添加至下周.NET周报

**Comment by InCerryGit** [comment]
- [ ] 添加至下周.NET周报

**Comment by InCerryGit** [comment]
已经添加至：https://www.cnblogs.com/InCerry/p/dotnet_week_23_2_3.html
