### ISSUE TITLE
[投稿]: dotnet DirectX 做一个简单绘制折线笔迹的 D2D 应用

### ISSUE THREAD

**Issue by lindexi** [InCerryGit/.NET-Weekly#10]
### 标题

dotnet DirectX 做一个简单绘制折线笔迹的 D2D 应用

### 链接

https://www.cnblogs.com/lindexi/p/18468855

### 简介

本文将告诉大家如何从简单的控制台开始，使用 Vortice 辅助调用 Direct2D1 的功能，配合 WM_Pointer 消息，制作一个简单绘制触摸折线笔迹的 D2D 应用

### 许可协议

- [X] 我同意将投稿内容授权给InCerry用于.NET周报的发布

**Comment by InCerryGit** [comment]
已收录，https://www.cnblogs.com/InCerry/p/-/dotnet_week_24_10_4
