### ISSUE TITLE
[投稿]: dotnet 简单聊聊 Skia 里的 SKFontMetrics 的各项属性作用

### ISSUE THREAD

**Issue by lindexi** [InCerryGit/.NET-Weekly#11]
### 标题

dotnet 简单聊聊 Skia 里的 SKFontMetrics 的各项属性作用

### 链接

https://www.cnblogs.com/lindexi/p/18621674

### 简介

本文将和大家简单聊聊 Skia 里的 SKFontMetrics 的各项属性作用和代表的含义

### 许可协议

- [X] 我同意将投稿内容授权给InCerry用于.NET周报的发布

**Comment by InCerryGit** [comment]
https://www.cnblogs.com/InCerry/p/-/dotnet_week_24_12_4
