### ISSUE TITLE
[投稿]: dotnet 简单使用 ICU 库进行分词和分行

### ISSUE THREAD

**Issue by lindexi** [InCerryGit/.NET-Weekly#12]
### 标题

dotnet 简单使用 ICU 库进行分词和分行

### 链接

https://www.cnblogs.com/lindexi/p/18622917

### 简介

本文将和大家介绍如何使用 ICU 库进行文本的分词和分行

### 许可协议

- [X] 我同意将投稿内容授权给InCerry用于.NET周报的发布

**Comment by InCerryGit** [comment]
https://www.cnblogs.com/InCerry/p/-/dotnet_week_24_12_4
