### ISSUE TITLE
C/C++包装器SWIG使用指南

### ISSUE THREAD

**Issue by Guyiming** [InCerryGit/.NET-Weekly#2]
* 标题(10-50字)：C/C++包装器SWIG使用指南
* 文章或项目访问链接：
[SWIG包装器使用指南——（一）基本概念](https://catshitone.blog.csdn.net/article/details/129838746)
[SWIG包装器使用指南——（二）C++代码的包装](https://catshitone.blog.csdn.net/article/details/129895200)
[SWIG包装器使用指南——（三）Typemap 类型映射](https://catshitone.blog.csdn.net/article/details/129896510)
[SWIG包装器使用指南——（四）C#使用SWIG简介与实践](https://catshitone.blog.csdn.net/article/details/129899584)
* 简介(200子以内)：
SWIG （Simplified Wrapper and Interface Generator）是一个exe小工具，主要用来包装已有的 C/C++ 代码并生成目标语言（C#、Java、Lua、Python等）代码。可以极大简化目标语言到C/C++的调用。上述文章对SWIG的使用做了基本介绍并结合C#调用到C++时的一些常见问题做了举例说明。

- [x] 任务：添加至下一期.NET周报

**Comment by InCerryGit** [comment]
不好意思，没有注意到这个信息，加入到下周周刊

**Comment by InCerryGit** [comment]
已加入本周周刊 https://www.cnblogs.com/InCerry/p/dotnet_week_23_7_3.html
