### ISSUE TITLE
C# - DTO 的字符串表达

### ISSUE THREAD

**Issue by TXRock** [InCerryGit/.NET-Weekly#3]
* 标题(10-50字)：【C#】DTO 的字符串表达 
* 文章或项目访问链接：https://www.cnblogs.com/txrock/p/16978098.html
* 简介(200子以内)：原本需要重写每个数据传输对象的 ToString 方法 JSON 序列化该对象，以便在日志中输出，在有了 record 以及 .NET 7 的加持之后，可以利用多态只写一次 ToString 方法或 record 自身的 ToString 达到同样的效果

- [x] 任务：添加至下一期.NET周报

**Comment by InCerryGit** [comment]
@TXRock  你好，我看这个时间是去年的，有没有最近的新文章呢？

**Comment by TXRock** [comment]
InCerry 你好，

最近发布的：https://www.cnblogs.com/txrock/p/17791189.html

摘要：用户在使用类库时，通常需要通过 VS 的 Intellisense 或 F12 反编译查看 API 的注释，借助这些注释来了解如何使用 API。在 C# 源文件中，可以通过编写由三斜杠表示的特殊注释字段，在代码中建立类库所需的 API 文档。注释字段包含用于描述其下方代码块的 XML 元素，XML 元素为 API 文档提供了结构化的格式，便于编译器等工具的解析。

**Comment by InCerryGit** [comment]
不好意思，之前遗漏了这个issue，添加到下一周的周报~

**Comment by InCerryGit** [comment]
已经添加到2月3期周报
