### ISSUE TITLE
添加到下一期的.NET周报中 - Roslyn 简单实现代码智能提示补全功能

### ISSUE THREAD

**Issue by lindexi** [InCerryGit/.NET-Weekly#4]
**请在下方填写内容**

* 标题(10-50字)： Roslyn 简单实现代码智能提示补全功能
* 文章或项目访问链接：https://www.cnblogs.com/lindexi/p/18365261 
* 简介(200子以内)：相信有很多伙伴热衷于编写 IDE 应用，在 dotnet 系下，通过 Roslyn 友好的 API 和强大的能力，实现一个代码智能提示是非常简单的事情。本文将和大家简单介绍一下如何使用 Roslyn 实现简单的代码智能提示补全功能

**如果有图片，记得先上传至图床，并给出图片链接。下面内容无需变动，只是提醒作者别忘记添加。**

- [x] 任务：添加至下一期.NET周报

**Comment by InCerryGit** [comment]
已收录
https://www.cnblogs.com/InCerry/p/-/dotnet_week_24_8_3
