### ISSUE TITLE
添加到下一期的.NET周报中 - 为何 Thread.Sleep 半毫秒和一毫秒等待时间差距如此之大

### ISSUE THREAD

**Issue by lindexi** [InCerryGit/.NET-Weekly#5]
**请在下方填写内容**

* 标题(10-50字)：为何 Thread.Sleep 半毫秒和一毫秒等待时间差距如此之大
* 文章或项目访问链接：https://www.cnblogs.com/lindexi/p/18381792 
* 简介(200子以内)：本文记录我读 dotnet 的源代码了解到为什么调用 Thread.Sleep 的时候，传入的是不足一毫秒，如半毫秒时或 0.99 毫秒，与传入是一毫秒时，两者的等待时间差距非常大

**如果有图片，记得先上传至图床，并给出图片链接。下面内容无需变动，只是提醒作者别忘记添加。**

- [ ] 任务：添加至下一期.NET周报

**Comment by InCerryGit** [comment]
https://www.cnblogs.com/InCerry/p/-/dotnet_week_24_8_4
