### ISSUE TITLE
添加到下一期的.NET周报中 - 从控制台开始 关联 Win2D 和 WinUI 3 应用

### ISSUE THREAD

**Issue by lindexi** [InCerryGit/.NET-Weekly#6]
**请在下方填写内容**

* 标题(10-50字)：从控制台开始 关联 Win2D 和 WinUI 3 应用
* 文章或项目访问链接：https://www.cnblogs.com/lindexi/p/18378612
* 简介(200子以内)：本文将告诉大家如何从最简单的控制台开始搭建，让 Win2D 和 WinUI 3 关联起来，让 Win2D 可以将内容渲染到 WinUI 3 应用上

**如果有图片，记得先上传至图床，并给出图片链接。下面内容无需变动，只是提醒作者别忘记添加。**

- [x] 任务：添加至下一期.NET周报

**Comment by InCerryGit** [comment]
https://www.cnblogs.com/InCerry/p/-/dotnet_week_24_8_4
