### ISSUE TITLE
添加到下一期的.NET周报中 - WPF 从裸 Win 32 的 WM_Pointer 消息获取触摸点绘制笔迹

### ISSUE THREAD

**Issue by lindexi** [InCerryGit/.NET-Weekly#7]
**请在下方填写内容**

* 标题(10-50字)：WPF 从裸 Win 32 的 WM_Pointer 消息获取触摸点绘制笔迹
* 文章或项目访问链接：https://www.cnblogs.com/lindexi/p/18390983
* 简介(200子以内)：本文将告诉大家如何在 WPF 里面，接收裸 Win 32 的 WM_Pointer 消息，从消息里面获取触摸点信息，使用触摸点信息绘制简单的笔迹

**如果有图片，记得先上传至图床，并给出图片链接。下面内容无需变动，只是提醒作者别忘记添加。**

- [x] 任务：添加至下一期.NET周报

**Comment by InCerryGit** [comment]
https://www.cnblogs.com/InCerry/p/-/dotnet_week_24_9_2
