### ISSUE TITLE
添加到下一期的.NET周报中 - dotnet 读 WPF 源代码笔记 从 WM_POINTER 消息到 Touch 事件

### ISSUE THREAD

**Issue by lindexi** [InCerryGit/.NET-Weekly#8]
**请在下方填写内容**

* 标题(10-50字)：dotnet 读 WPF 源代码笔记 从 WM_POINTER 消息到 Touch 事件
* 文章或项目访问链接：https://www.cnblogs.com/lindexi/p/18403860
* 简介(200子以内)：本文记录我读 WPF 源代码的笔记，在 WPF 底层是如何从 Win32 的消息循环获取到的 WM_POINTER 消息处理转换作为 Touch 事件的参数 

**如果有图片，记得先上传至图床，并给出图片链接。下面内容无需变动，只是提醒作者别忘记添加。**

- [x] 任务：添加至下一期.NET周报

**Comment by InCerryGit** [comment]
https://www.cnblogs.com/InCerry/p/-/dotnet_week_24_9_2
